storage: verdaccio/storage
plugins: verdaccio/plugins
web:
  # I am not adding too much customisation to the proxy registry for now
  title: MK Registry
  # comment out to disable gravatar support
  gravatar: false
  darkMode: true
  html_cache: true
  showInfo: false
  showThemeSwitch: false
  showFooter: false
auth:
  htpasswd:
    file: verdaccio/htpasswd
# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
server:
  keepAliveTimeout: 60
middlewares:
  audit:
    enabled: true
# log settings
logs: { type: stdout, format: pretty, level: http }
